name: test workflows

on: 
  push:
    branches:
      - man
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm i
      - name: Run linting
        run:  npx eslint .
      - name: Run build
        run:  npm run build
      - name: Run tests
        run:  npm test
  deploy_app:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy 
        run: echo "Deployed"